[package]
name = "entra-auto-activate"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
thirtyfour = "0.35.0"
clap = { version = "4.5.40", features = ["derive"] }
