# .github/workflows/release.yml

on:
  release:
    types: [created]

permissions:
    contents: write
    checks: write
    actions: read
    issues: read
    packages: write
    pull-requests: read
    repository-projects: read
    statuses: read

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - name: Install Linux and Windows Cross Compilers
        run: sudo apt-get install --yes --no-install-recommends musl-tools gcc-mingw-w64-x86-64-win32

      - name: Install rustup targets
        run: rustup target add x86_64-pc-windows-gnu

      - name: Build the executable
        run: cargo build --release --target x86_64-pc-windows-gnu

      - name: Zip windows binary
        run: zip -j entra-auto-activate.zip target/x86_64-pc-windows-gnu/release/entra-auto-activate.exe

      - name: Generate SHA256 checksums
        run: |
          shasum -a 256 entra-auto-activate.zip > entra-auto-activate.zip.sha256

      - name: Upload release binaries
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["entra-auto-activate.zip", "entra-auto-activate.zip.sha256"]'